apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: k8s-3tier
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  APP_MESSAGE: "Hello from ConfigMap! Hope you're having a great day!"
